matcher:
  KDTreeMatcher:
    knn: 15
    maxDist: 1
    epsilon: 1

outlierFilters:
  - TrimmedDistOutlierFilter:
      ratio: 0.8
  #  - RobustOutlierFilter:
  #     tuning: 2
  #     robustFct: "cauchy"
  #     scaleEstimator: "mad"
  - SurfaceNormalOutlierFilter:
      maxAngle: 0.7

errorMinimizer:
  PointToPlaneErrorMinimizer:
    force4DOF: 0

transformationCheckers:
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.001
      minDiffTransErr: 0.01
      smoothLength: 2
  - CounterTransformationChecker:
      maxIterationCount: 40
  - BoundTransformationChecker:
      maxRotationNorm: 2.5
      maxTranslationNorm: 20.0

inspector: NullInspector

logger: NullLogger
